server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://34.245.193.199:3100/loki/api/v1/push

scrape_configs:
  - job_name: production_app
    static_configs:
      - targets:
          - localhost
        labels:
          job: app_logs
          host: production
          __path__: /app_logs/*.log

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: production
          __path__: /var/log/*.log